### PR TITLE
Make esm-amd-loader dynamic require 404 test not flaky.

### LINKED ISSUE #507: esm-amd-loader 404s test is flaky
The "calls error callback only once on multiple 404s" test appears to be flaky. I keep seeing different browsers fail this test on CI:

```
OS X 10.13 safari latest ✖ static/y/suite.html » dynamic require » calls error callback only once on multiple 404s
  expected 0 to equal 1
    <unknown> at                      AssertionError at /components/wct-browser-legacy/node_modules/chai/chai.js:5260:0
    <unknown> at                              assert at /components/wct-browser-legacy/node_modules/chai/chai.js:259:0
    <unknown> at                               equal at /components/wct-browser-legacy/node_modules/chai/chai.js:2006:0
    <unknown> at   http://localhost:8000/components/ at polymer/esm-amd-loader-test/lib/suite.js:225:0
chrome 67                Tests passed
Windows 8.1 IE 11        Beginning tests via http://localhost:8000/components/@polymer/esm-amd-loader-test/generated-index.html?cli_browser_id=0
firefox 60               Tests passed
OS X 10.13 safari latest Tests failed: 1 failed tests
Windows 10 microsoftedge latest Tests passed
Windows 8.1 IE 11        Tests passed
Test run ended in failure: 1 failed tests
```

### PR DESCRIPTION
**Pull request by aomarks**
Previously this test used a 1 second timeout to wait to see how many times the error callback was called, which was flaky on CI. Now we capture 404 errors and check callback calls after two 404s.

Fixes #507

(Note first commit is just clang formatting).

### CODE REVIEW

File: packages/esm-amd-loader/test/src/suite.ts [hunk 1]
```diff
@@ -268,19 +268,25 @@ suite('dynamic require', () => {
...
 
   test('calls error callback only once on multiple 404s', (done) => {
-    let numErrors = 0;
+    let num404s = 0;
+    let numCallbackCalls = 0;
+
+    window.addEventListener('error', on404, true);
+
+    function on404() {
+      if (++num404s === 2) {
```
Comment (rictic) [inline packages/esm-amd-loader/test/src/suite.ts]: Prefer inert conditionals.

```typescript
num404s++;
if (num404s === 2) {
  ...
```

File: packages/esm-amd-loader/test/src/suite.ts [hunk 2]
```diff
@@ -268,19 +268,25 @@ suite('dynamic require', () => {
   });
 
   test('calls error callback only once on multiple 404s', (done) => {
-    let numErrors = 0;
+    let num404s = 0;
+    let numCallbackCalls = 0;
+
+    window.addEventListener('error', on404, true);
```
Comment (rictic) [inline packages/esm-amd-loader/test/src/suite.ts]: Hm, I don't think this is the expected behavior. `require` should not throw a global error, it should only call the failure callback shouldn't it?

File: packages/esm-amd-loader/test/src/suite.ts [hunk 3]
```diff
@@ -268,19 +268,25 @@ suite('dynamic require', () => {
...
+        done();
+      }
+    }
 
     define(['require'], (require: any) => {
       require(
           ['./not-found-a.js', './not-found-b.js'],
           () => assert.fail(),
-          () => numErrors++);
+          () => numCallbackCalls++);
```
Comment (rictic) [inline packages/esm-amd-loader/test/src/suite.ts]: Hm, what we really want to do is wait for the first error callback, and consider the test a success if the error callback isn't called again within the next little while (i.e. using setTimeout).

That should be non-flaky.

File: packages/esm-amd-loader/test/src/suite.ts (hunk 2 above)
Comment (rictic) [reply packages/esm-amd-loader/test/src/suite.ts]: Oh, is this the browser doing this? Emitting a window error?

Comment (aomarks) [reply packages/esm-amd-loader/test/src/suite.ts]: Yeah, you can capture the browser network errors by adding the capture phase listener (the true).

File: packages/esm-amd-loader/test/src/suite.ts (hunk 3 above)
Comment (aomarks) [reply packages/esm-amd-loader/test/src/suite.ts]: IIUC that would be more error prone (since network latency between the two fetches could cause the test to incorrectly pass) and slower (since we have to wait for the timeout).

File: packages/esm-amd-loader/test/src/suite.ts (hunk 1 above)
Comment (aomarks) [reply packages/esm-amd-loader/test/src/suite.ts]: Done.

File: packages/esm-amd-loader/test/src/suite.ts (hunk 3 above)
Comment (aomarks) [reply packages/esm-amd-loader/test/src/suite.ts]: I did need to add a tick to let the error handlers get called though. Seems reliably green on sauce now, will see what CI says.
